### ISSUE TITLE
TypeError: 'null' is not a function (evaluating 'jasmine.Ajax.requests.mostRecent().response

### ISSUE THREAD

**Issue by cliren** [jasmine/jasmine-ajax#88]
//code

jasmine.Ajax.requests.mostRecent().response({
'status': 200,
'responseText': data
});

The following error is thrown with using latest (2.99.0) jasmine-ajax. Works fine with jasmine-ajax@2.0.2

TypeError: 'null' is not a function (evaluating 'jasmine.Ajax.requests.mostRecent().response({
          'status': 200,
          'responseText': data
        })')

**Comment by panSarin** [comment]
I have simliar problem
There are my source code:

https://gist.github.com/panSarin/3ebfb26550854267c972

and i have error: 

TypeError: object is not a function
    at Object.<anonymous> (file:///home/ap/projects/jasmine/spec/MyRequestsSpec.js:18:13)

**Comment by slackersoft** [comment]
@panSarin I'm not able to duplicate your results when running with jasmine-ajax 2.99 which is the most recently released version. If you are using master off of github, the `response` method has been removed  and replaced with `respondWith` so we don't collide with XHR 2's `response` property.

**Comment by slackersoft** [comment]
@cliren I haven't been able to reproduce the error you're seeing. Do you know which part of that line is actually returning `null`?

**Comment by philipgiuliani** [comment]
I'm having the same error currently. For me `.mostRecent()` is returning undefined.

**Comment by slackersoft** [comment]
@philipgiuliani It sounds like you're getting a slightly different error. The other errors seem to be calling `response` which is no longer a function, but now a normal property to more closely mimic real XHR behavior.

If you're seeing `mostRecent()` return `undefined` it means that jasmine-ajax hasn't actually tracked a request since it's been turned on. Do you have some other ajax mocking thing that might be blocking the request from actually making an `XmlHttpRequest`?

**Comment by phun-ky** [comment]
@slackersoft seems to me that, if you have several jasmine specs containing `jasmine.Ajax.install`, they all will conflict with each other. I'm using karma to run the tests, but to narrow the scope, I only test this spec:

describe('api', function() {

      var api;
      var _loadUserDetailsMock = require('../../../mockdata/userDetailsResponse.ajax-mock.js');
      var _load_user_details_request;


      beforeEach(function() {

        jasmine.Ajax.install();

      });

      describe('loadUserDetails()', function(){

        beforeEach(function(){

          api = require('../api');
          api.accessToken = '123';

          spyOn(api,'ensureAccessToken');
          spyOn(api,'loadUserDetails');

        });

        it('loads the correct user details', function(){

          api.loadUserDetails();
          _load_user_details_request = jasmine.Ajax.requests.mostRecent();

          expect(api.ensureAccessToken).toHaveBeenCalled();
          expect(api.loadUserDetails).toHaveBeenCalled();
          _load_user_details_request.respondWith(_loadUserDetailsMock.search.success);

        });

      });

    });

No other specs are loaded, and I am including the ajax-mock-script with karma. 

I'm getting same error as @philipgiuliani : 

    TypeError: Cannot read property 'respondWith' of undefined

**Comment by phun-ky** [comment]
I found something regarding the error @philipgiuliani and I have. If you are spying on the method calling `$.ajax` (in essential, any XHTMLRequest), you will get the error mentioned, with this spec (updated from the comment above):

    describe('api', function() {

      var api;
      var _loadUserDetailsMock = require('../../../mockdata/userDetailsResponse.ajax-mock.js');
      var _load_user_details_request;


      beforeEach(function() {

        jasmine.Ajax.install();

      });

      describe('loadUserDetails()', function(){

        beforeEach(function(){

          api = require('../api');
          api.accessToken = '123';

          spyOn(api,'ensureAccessToken');
          //spyOn(api,'loadUserDetails');

        });

        it('loads the correct user details', function(){
          // loadUserDetails contains an $.ajax()-call
          api.loadUserDetails();
          _load_user_details_request = jasmine.Ajax.requests.mostRecent();

          expect(api.ensureAccessToken).toHaveBeenCalled();
          //expect(api.loadUserDetails).toHaveBeenCalled();
          _load_user_details_request.respondWith(_loadUserDetailsMock.search.success);

        });

      });

    });

It works! Bug? Feature? If this is a feature, clearly specify this in the documentation please :)

**Comment by slackersoft** [comment]
If you've spied on the function that actually makes the XHR, then the XHR won't actually be created and jasmine-ajax has no way of intercepting an ajax request that isn't actually made. The spy has effectively already intercepted the request anyways, so jasmine-ajax' method of interception is unnecessary in that case.

I'm not sure what kind of documentation would be useful for this case.

**Comment by phun-ky** [comment]
@slackersoft *facepalm*

Fixed my issue with adding:

    .and.passThrough()

To the spies. Thanks for the patience ;) keep up the good work

**Comment by slackersoft** [comment]
Closing this then. It sounds like it was mostly a spy blocking the XHR from being created.

Please open another issue if you're still having problems.

thanks for using jasmine!
